spring.application.name=back

# MySQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis
mybatis.mapper-locations=classpath:mappers/*.xml

#JWT
#accessToken=15s, refreshToken=7d
jwt.secret=${JWT_SECRET}
jwt.accessToken-expiration=900000
jwt.refreshToken-expiration=604800000

#Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

#TMDB
tmdb.api.key=${TMDB_API_KEY}