spring.application.name=back

# MySQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis
mybatis.mapper-locations=classpath:mappers/*.xml

#JWT
#accessToken=15s, refreshToken=7d
jwt.secret=${JWT_SECRET}
jwt.accessToken-expiration=900000
jwt.refreshToken-expiration=604800000

#Redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}

#TMDB
tmdb.api.key=${TMDB_API_KEY}